# https://circleci.com/docs/2.0/configuration-reference/
version: 2
jobs:
  build:
    docker:
      # https://hub.docker.com/_/node
      - image: node:16-alpine3.12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v16-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v16-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v16-dependencies-{{ checksum "package.json" }}

      - run: npm test
