# https://circleci.com/docs/configuration-reference/
version: 2
jobs:
  build:
    docker:
      # https://circleci.com/developer/images/image/cimg/node
      - image: cimg/node:22

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v22-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v22-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v22-dependencies-{{ checksum "package.json" }}

      - run: npm test
