# https://circleci.com/docs/2.0/configuration-reference/
version: 2
jobs:
  build:
    docker:
      - image: node:current-alpine
      #- image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
